### ISSUE TITLE
Implement DA fetching from a provider

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/hotshot-query-service#337] opened 2024-01-08 20:03 UTC
Implement fetching from a provider. This will come next, once we're satisfied with the architecture, since a fetching implementation can just be dropped into the hole in this PR: Fetchable::active_fetch

**Comment by jbearer** [comment] 2024-01-19 17:10
Duplicate of #326

**Closed by jbearer** 2024-01-19 17:10 UTC
Labels: da-recovery, cappuccino, cappuccino-sprint1
